spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capacity_planner
    username: capacity_user
    password: cap123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080